(function setRandomSplashTitle() {
    const splashes = [
        "also try terraria!",
        "100% organically grown",
        "typescript <3",
        "ZA WARUDO!!!",
        "not a virus, promise!",
        "i have three dollars",
        "hakuna matata!",
        "hello, world!",
        "less than three <3",
        "conga conga conga",
        "tetris forever!",
        "10,003,008,528^42",
        "this is a splash text",
        "trees are cool guys",
        "google.com (ha ha jk)",
        "opera is a good browser",
        "if i fall, i think i'll fly",
        "scott pilgrim versus the world",
        "blood for the blood god",
        "up up down down left right left right b a",
        "waluigi time",
        "this is line 27 of splash.js speaking",
        "euclid was a genius",
        "attack on titan is overrated",
        "tom marvolo riddle me this batman",
        "peanut butter jelly time!",
        "club penguin is kil :<",
        "i am sorry if this makes no sense",
        "o_o dude wtf???",
        "check this out",
        "i think i am dying",
        "do a flip!",
        "every pokemon vs 10 billion lions",
        "this is crazy man",
        "abracadabra!",
        "wait wait wait wait wait",
        "ampersand &",
        "what is your favorite pokemon?",
        "you came from linkedin, didn't you?",
        "coffee is overrated",
        "diet coke sucks",
        "to sql or nosql",
        "i am shakespeare",
        "({[]})",
        "house robber",
        "1337",
        "congratulations, you won an IPHONE!",
        "open the door!",
        "knock knock!",
        "who's there?",
        "your ex!",
        "your ex who?",
        "your existential crisis, wake up!",
        "i am in your walls :)",
        "spiderman spiderman does whatever a spider can",
        "self-implied oxymoron",
        "subatomic particle",
        "man, i don't know",
        "im a punkrocker, yes i am!",
        "nice.",
        "good heavens!",
        "by jove!",
        "mayday! mayday!",
        "please stop reloading the page...",
        "ai is no match for my organic tomfoolery",
        "AAAAAAAAAAAAAAAAAHHHHHHHHHH",
        "this page is haunted",
        "france",
        "drink water",
        "you look very tired",
        "excuse me, do you need some help?",
        "go to sleep!",
        "touch grass!",
        "freeware!",
        "this is open source!",
        "double down!",
        "pew pew pew!"
    ];

    const randomIndex = Math.floor(Math.random() * splashes.length);
    const randomSplash = splashes[randomIndex];

    document.title = randomSplash;
})();
