(function setRandomSplashTitle() {
    const splashes = [
        "also try terraria!",
        "100% organically grown",
        "typescript is amazing",
        "ZA WARUDO!!!",
        "i have three dollars",
        "hakuna matata!",
        "hello, world!",
        "less than three <3",
        "conga conga conga",
        "tetris forever!",
        "10,003,008,528^42",
        "this is a splash text",
        "trees are cool guys",
        "google.com (ha ha jk)",
        "opera is a good browser",
        "if i fall, i think i'll fly",
        "scott pilgrim versus the world",
        "blood for the blood god",
        "up up down down left right left right b a",
        "waluigi time",
        "this is line 27 of splash.js speaking",
        "euclid was a genius",
        "attack on titan is overrated",
        "tom marvolo riddle me this batman",
        "peanut butter jelly time!",
        "club penguin is kil :<",
        "i am sorry if this makes no sense",
        "o_o dude wtf???",
        "check this out",
        "i think i am dying",
        "do a flip!",
        "every pokemon vs 10 billion lions",
        "this is crazy man",
        "abracadabra!",
        "wait wait wait wait wait",
        "what is your favorite pokemon?",
        "you came from linkedin, didn't you?",
        "coffee is overrated",
        "diet coke sucks",
        "to sql or nosql",
        "shakespeare is shaking in his grave",
        "house robber",
        "1337",
        "congratulations, you won an IPHONE!",
        "open the door!",
        "knock knock!",
        "who's there?",
        "your ex!",
        "your ex who?",
        "your existential crisis, wake up!",
        "i am in your walls :)",
        "self-implied oxymoron",
        "man, i don't know",
        "im a punkrocker, yes i am!",
        "nice.",
        "good heavens!",
        "by jove!",
        "mayday! mayday!",
        "please stop reloading the page...",
        "freshly baked tomfoolery",
        "AAAAAAAAAAAAAAAAAHHHHHHHHHH",
        "this page is haunted",
        "france",
        "drink water",
        "you look very tired",
        "go to sleep!",
        "touch grass!",
        "this is open source!",
        "pew pew pew!",
        "do you want to have a bad time?",
        "bread butter and peanut butter",
        "it takes ten to know one",
        "setRandomSplashTitle!",
        "pretend i said something funny",
        "imagine using <title> for titles",
        "i am inevitable!",
        "hoo boy!",
        "your daily dose of uh this",
        "pleasure to meet you",
        "smooth jazz!",
        "aggressive jazz!",
        "honey mustard my beloved",
        "trust me bro",
        "what.",
        "LOUD and ",
        "SQL injection proof!",
        "THIS IS SPARTA!!!",
        "who goes there?",
        "she sells seashells by the seashore",
        "beep boop",
        "cue the music!",
        "welcome to the funny page",
        "the (actual) front page of the internet!",
        "i can do this all day",
        "on your left!",
        "doorknob.",
        "CHOCOLATE?!?!?!",
        "shmebulock",
        "i cast vicious mockery",
        "TACTICAL NUKE INCOMING",
        "tabs over spaces",
        "cover me in open sauce",
        "you must ponder the orb",
        "confidently unsure",
        "watch rango, good movie",
        "kid with a sword",
        "also try vvvvvv!",
        "also try cuphead!",
        "also try super meat boy!",
        "pasta with no sauce",
        "diamond minecarts",
        "amsterdamn",
        "mmmm, monke",
        "donate blood today!",
        "solar powered (not really)",
        "feel free to hate this site",
        "repeat but less louder please",
        "wubba lubba dub dub!",
        "blackjack and hookers",
        "good news, everyone!",
        ":P (that's a cap, not my tongue, look again)",
        "also try super smash flash!",
        "fifteen squared",
        "stop for a second",
        "death by glamour",
        "his face all red",
        "visit falsepositivecomic.com today!",
        "visit totaljerkface.com today!"
    ];

    const randomIndex = Math.floor(Math.random() * splashes.length);
    const randomSplash = splashes[randomIndex];

    document.title = randomSplash;
})();
